#!/bin/bash

if   [[ "$OSTYPE" == "linux-gnu" ]]; then
   #
         echo "Yeah!"
   #
if   [[ "$OSTYPE" == "linux-android" ]]; then
   #
         echo "termux"
   #
elif [[ "$OSTYPE" == "darwin"* ]]; then
   #
         echo "Mac OSX"
   #
elif [[ "$OSTYPE" == "cygwin" ]]; then
   #
         echo "POSIX environment emulation for Windows"
   #
elif [[ "$OSTYPE" == "msys" ]]; then
   #
         echo "Shell for MinGW"
   #
elif [[ "$OSTYPE" == "win32" ]]; then
   # 
   #     Can OSTYPE ever be win32?
         echo "Windows"
   #
elif [[ "$OSTYPE" == "freebsd" ]]; then
   #
         echo "Hm...???"
   #
elif [[ "$OSTYPE" == "openbsd" ]]; then
   #
         echo "Hm...???"
   #
elif [[ "$OSTYPE" == "solaris" ]]; then
   #
         echo "Well..."
   #
elif [[ "$OSTYPE" == "haiku" ]]; then
   #
         echo "Well, well, well, the cat fell in the well"
   #
else
   #
         echo "Unknown OSTYPE $OSTYPE"
   #
fi
